FROM jdcook/symfony1:build1 as builder

FROM php:8.1-apache

RUN a2enmod rewrite

RUN docker-php-ext-install -j$(nproc) pdo_mysql opcache

RUN mkdir /code && mkdir /code/var && chmod 777 /code/var

WORKDIR /code

COPY . .
COPY --from=builder /code/vendor ./vendor

ENV APACHE_DOCUMENT_ROOT /code/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
